name: ci-pandora-capital-management-api

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Start CI process
      run: | 
        echo "Start CI process"
        
    - name: Listing files
      run: | 
        echo "Listing files:"
        ls -al
        
    - name: Python versions
      run: |
        echo "Python versions"
        ls -1 /usr/bin/python* | grep '[2-3].[0-9]$'
